# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterIndexTogether(
            name='helprequest',
            index_together=set([('time', 'type')]),
        ),
    ]
